### ISSUE TITLE
Incorrect imports in DataAnalyzer notebook

### ISSUE THREAD

**Issue by peterhessey** [Project-MONAI/tutorials#1083]
The imports in under "Setup Imports" in the [DataAnalyzer Notebook](https://github.com/Project-MONAI/tutorials/blob/main/auto3dseg/notebooks/data_analyzer.ipynb) are incorrect / outdated. Currently the DataAnalyzer import in the notebook is:

`from monai.apps.auto3dseg import DataAnalyzer`

but I believe the correct import is (at least for me, running `monai==1.0.1`) is:

`from monai.apps.auto3dseg.data_analyzer import DataAnalyzer`

**Comment by wyli** [comment]
thanks for reporting, the class is also part of `monai.apps.auto3dseg` because of this init file https://github.com/Project-MONAI/MONAI/blob/d0db5fd9d4da3bc7027d22c52bb9c405c3b9e879/monai/apps/auto3dseg/__init__.py#L14 

I can't reproduce this issue, and if you see any import error, perhaps you can try uninstalling any previous monai versions with `pip uninstall monai-weekly` and `pip uninstall monai`

**Comment by peterhessey** [comment]
Gotcha, thank you!
