### ISSUE TITLE
Cannot import name 'ImageDataset'

### ISSUE THREAD

**Issue by Meddebma** [Project-MONAI/tutorials#125]
Hi, 

I tried to implement the class ImageDataset after installing the newest Monai 0.4.0 for "unet_training_array.py", but I got the message "Cannot import name 'ImageDataset'". Should I install other modules?

Thanks

**Comment by rijobro** [comment]
Hi, `ImageDataset` is a newer class that was made to replace e.g., `NiftiDataset`. If you are using MONAI 0.4.0, then checking out the 0.4.0 tag of the tutorials should solve the problem. Or, to use the master branch of the tutorials, get a more recent version of MONAI with, for example, `pip install monai-weekly`.

**Comment by Meddebma** [comment]
Dear @rijobro, 
thanks for your answer, still did not work, here is the link to the code, did I do something wrong?

https://github.com/Meddebma/pyradiomics/blob/master/Spleen2021.ipynb

**Comment by rijobro** [comment]
Hi, I'm not sure what the problem is, but it looks like something is wrong with that weekly build. In your notebook, I changed this:

```python
%pip install monai-weekly
```

to this:

```python
%pip uninstall monai -y
%pip install git+https://github.com/Project-MONAI/MONAI#egg=MONAI
```
and then restarted the notebook and it seemed to work. Let me know if that doesn't sort it for you too. Since the weekly builds change on a weekly basis, hopefully the problem that you noticed will disappear in the next few days anyway.

**Comment by Meddebma** [comment]
Hi @rijobro,
thanks after several tries it worked! 
Best, Aymen
