### ISSUE TITLE
volume matrix

### ISSUE THREAD

**Issue by oscarramirezs** [Project-MONAI/tutorials#127]
hi,

I am training a model to segment a knee,

the problem is that each image is a 512 * 512 matrix, but each CT has a different number of images eg (512 * 512 * 200) (512 * 512 * 500), sometimes the CT goes up to the hip and sometimes is only knee,

How can I standardize so that all CTs have the same matrix?
 and what I can do with CTs that go up to the hip, which can have up to 5 times more images.

becouse the literature suggests always using the same volume matrix

thank for your hepl 

Oscar

**Comment by rijobro** [comment]
The easiest thing to do here is to crop/pad so that all are the same size with `ResizeWithPadOrCrop`. Just pick the size and they'll all be the same size.

Slightly more complicated is your second question "what I can do with CTs that go up to the hip?" If you know that the knee is always in the centre image you could use `SpatialCrop` to centre crop around that, or if you knew the knee was at the bottom of the image, you could use `SpatialCrop` to crop the edge. But both of these imply that you know _a priori_ the location of all the knees in your images.

**Comment by rijobro** [comment]
In future, please ask these sorts of questions in the Discussions tab of our main repository: https://github.com/Project-MONAI/MONAI/discussions
