### ISSUE TITLE
deepgrow files not present

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/tutorials#169]
Deepgrow tutorials need files that are not present to run, see here: https://github.com/Project-MONAI/MONAI/runs/2243105725?check_suite_focus=true#step:6:298.

**Comment by rijobro** [comment]
@SachidanandAlle Do you think you could have a look at this?

**Comment by wyli** [comment]
not sure we'll get this fixed. I'm trying to use the option of `runner.sh -p` to exclude the deepgrow files from the tests. but not sure how to set the arg. @rijobro any idea?  otherwise let's move the tutorials out of the repo because we couldn't maintain those.

**Comment by SachidanandAlle** [comment]
the deepgrow inference notebook needs pretrained models (for 2D and 3D) and sample image..
if there is some place in aws or so.. if we can push them, then we can download and access it as part of notebooks run.

https://drive.google.com/drive/folders/1lypRGUoybX5detODnt2QnWC_j_Xkw2ys?usp=sharing
Here we need deepgrow_2d.ts, deepgrow_3d.ts and _image.nii.gz) to be available through wget kind to access them in notebooks (instead of g-drive)

**Comment by wyli** [comment]
ok these files are useful, monai provides function to download from gdrive

**Comment by rijobro** [comment]
I agree that the easiest thing to do is simply to download them from gdrive provided they won't be deleted any time soon.

**Comment by rijobro** [comment]
https://github.com/Project-MONAI/MONAI/blob/master/monai/apps/utils.py#L74-L112

**Comment by wyli** [comment]
```py
from monai.apps import download_url

resource = "https://drive.google.com/uc?export=download&id=1xRHGm9kUvRLEWeWeGj9EmYc9EEy77cEg"
dst = os.path.join("..", "bentoml", "classifier.zip")
if not os.path.exists(dst):
    download_url(resource, dst)
```

**Comment by YuanTingHsieh** [comment]
Should be fixed by the above PR.

**Comment by YuanTingHsieh** [comment]
Actually two questions here:

1. I don't have ``%pip install gdown`` in the top. Do we want to add that?
2. Do we want to include the output (those graphs and execution result of each cell) into the notebook?
