### ISSUE TITLE
How to handle RGB 2D images

### ISSUE THREAD

**Issue by mangotee** [Project-MONAI/tutorials#65]
**Describe the bug**
I just tried running the 2D segmentation tutorial, but on my own 2D images (a mixed dataset of TIFF, PNG, JPG and BMP images). I ran into several problems, e.g. LoadPNGd cannot handle TIFF images, the rest of the transform pipeline throws an error (I think PIL loads TIF images in a different way than others - I usually use `skimage.io`, which always returns a numpy array). The biggest problem though is that the transforms pipeline cannot handle the color channel in RGB images, or I am doing sth wrong when applying the `Resized()` transform - the latter is necessary because I need images at a fixed size of 320x240 at the end of the transform pipeline.

**To Reproduce**
Put a few RGB color images (maybe including at least one TIFF image ;) into a directory, then set up a simple transform pipeline like this:

    train_transforms = Compose(
        [
            LoadImaged(keys=["img"]),
            LoadNumpyd(keys=["seg"]), # my segs are four channels stored as numpy array, of shape (height,width,4)
            ScaleIntensityd(keys="img"),
            Resized(keys=["img", "seg"], spatial_size=(240,320), mode='bilinear', align_corners=True),
            RandFlipd(keys=["img", "seg"], prob=0.5),
            ToTensord(keys=["img", "seg"]),
        ]
    )

Then, to check the shape of the output tensors:

    # define check dataset, check data loader
    check_ds = monai.data.Dataset(data=train_files, transform=train_transforms)
    # use batch_size=2 to load images and use RandCropByPosNegLabeld to generate 2 x 4 images for network training
    check_loader = DataLoader(check_ds, batch_size=2, num_workers=4, collate_fn=list_data_collate)
    check_data = monai.utils.misc.first(check_loader)
    print(check_data["img"].shape, check_data["seg"].shape)
    plt.imshow(np.squeeze(check_data["img"][0,0,:,:]))

**Expected behavior**
If the color channel is handled correctly, I expect the shape of the tensors to be [2,3,240,320]. 

**Observed behavior**
The output shape is [2,300,240,320] (please note that in my case, `monai.utils.misc.first(check_loader)` loads an image of shape [300,400,3]).

**Environment (please complete the following information):**
 - Ubuntu 18.04
 - MONAI version: 0.2.0+166.g12b3fbf
 - Python version: 3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21)  [GCC 7.3.0]
 - Numpy version: 1.19.1
 - Pytorch version: 1.7.0a0+8deb4fe
 - Optional dependencies:
 - Pytorch Ignite version: 0.3.0
 - Nibabel version: 3.1.1
 - scikit-image version: 0.15.0
 - Pillow version: 7.2.0
 - Tensorboard version: 1.15.0+nv
 - gdown version: 3.12.2
 - TorchVision version: 0.8.0a0
 - ITK version: 5.1.1

**Comment by ericspod** [comment]
TIFF files are often an issue since it's just a broad definition. Typically we want to get 3D images from photographi files with shape (width, height, channel) where channel is 3 for RGB or 4 for RGBA typically. There are more exotic formats that will have 2 channels for alpha+luminance or other things, but TIFF and others might have a shape (width, height) if they are just greyscale. One solution to this is to have a transform which adds a 1-size channel if the image is 2D. With this regularized you now need to transpose the images so that they are in (channel, height, width) or (channel, width, height) format to match the Pytorch expectation of channel first, that's why the spatial tranforms misbehave as they are treating the channel dimension as a spatial one. 

This sequence of transforms will do this for a sequence of images, the dictionary versions are present in MONAI to do the same with your dictionary data:
```py
test_transforms = Compose(
    [
        LoadImage(image_only=True, reader=PILReader()),
        Lambda(lambda im: im[...,None] if im.ndim==2 else im),
        AsChannelsFirst(),
        Resize(crop_size, "area"),
        ToTensor(),
    ]
)
```

**Comment by mangotee** [comment]
Yes, adding `AsChannelFirstd(keys=["img", "seg"])` to the transforms list did the trick. 
Thanks also for the info regarding TIFFs. It's an image format that I come across rarely. I realized that LoadImaged (ITK image loader) can handle TIFs nicely, and I wrote a class that converts it numpy and makes sure that there are 3 color channels... but in the end I just decided to convert those few TIFFs in my training set to PNG, since I don't expect them to come up during deployment. Thanks anyway for the quick help!
