### ISSUE TITLE
nightly test error `deepedit/ignite/infoANDinference.ipynb`

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/tutorials#695]
**Describe the bug**
```
03:33:45  Running ./deepedit/ignite/infoANDinference.ipynb
03:33:45  Checking PEP8 compliance...
03:33:46  Running notebook...
03:33:46  Error: Couldn't find the keyword "max_epochs", and the notebook wasn't on the list of expected exemptions ("doesnt_contain_max_epochs")..
03:33:46  
03:33:46  Check failed!
03:33:46  /opt/conda/lib/python3.8/site-packages/papermill/iorw.py:58: FutureWarning: pyarrow.HadoopFileSystem is deprecated as of 2.0.0, please use pyarrow.fs.HadoopFileSystem instead.
03:33:46    from pyarrow import HadoopFileSystem
03:34:12  
Executing:   0%|          | 0/11 [00:00<?, ?cell/s]
Executing:   9%|▉         | 1/11 [00:01<00:15,  1.58s/cell]
Executing:  27%|██▋       | 3/11 [00:10<00:28,  3.58s/cell]
Executing:  45%|████▌     | 5/11 [00:12<00:13,  2.31s/cell]
Executing:  73%|███████▎  | 8/11 [00:21<00:08,  2.68s/cell]
Executing:  82%|████████▏ | 9/11 [00:24<00:05,  2.73s/cell]
Executing:  91%|█████████ | 10/11 [00:24<00:02,  2.24s/cell]
Executing:  91%|█████████ | 10/11 [00:25<00:02,  2.59s/cell]
03:34:12  Traceback (most recent call last):
03:34:12    File "/opt/conda/bin/papermill", line 8, in <module>
03:34:12      sys.exit(papermill())
03:34:12    File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
03:34:12      return self.main(*args, **kwargs)
03:34:12    File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1053, in main
03:34:12      rv = self.invoke(ctx)
03:34:12    File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
03:34:12      return ctx.invoke(self.callback, **ctx.params)
03:34:12    File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 754, in invoke
03:34:12      return __callback(*args, **kwargs)
03:34:12    File "/opt/conda/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
03:34:12      return f(get_current_context(), *args, **kwargs)
03:34:12    File "/opt/conda/lib/python3.8/site-packages/papermill/cli.py", line 250, in papermill
03:34:12      execute_notebook(
03:34:12    File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 122, in execute_notebook
03:34:12      raise_for_execution_errors(nb, output_path)
03:34:12    File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
03:34:12      raise error
03:34:12  papermill.exceptions.PapermillExecutionError: 
03:34:12  ---------------------------------------------------------------------------
03:34:12  Exception encountered at "In [6]":
03:34:12  ---------------------------------------------------------------------------
03:34:12  RuntimeError                              Traceback (most recent call last)
03:34:12  Input In [6], in <cell line: 3>()
03:34:12        1 # Evaluation
03:34:12        2 model_path = 'pretrained_deepedit_dynunet-final.ts'
03:34:12  ----> 3 model = jit.load(model_path)
03:34:12        4 model.cuda()
03:34:12        5 model.eval()
03:34:12  
03:34:12  File /opt/conda/lib/python3.8/site-packages/torch/jit/_serialization.py:161, in load(f, map_location, _extra_files)
03:34:12      159 cu = torch._C.CompilationUnit()
03:34:12      160 if isinstance(f, str) or isinstance(f, pathlib.Path):
03:34:12  --> 161     cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
03:34:12      162 else:
03:34:12      163     cpp_module = torch._C.import_ir_module_from_buffer(
03:34:12      164         cu, f.read(), map_location, _extra_files
03:34:12      165     )
03:34:12  
03:34:12  RuntimeError: 
03:34:12  Unknown builtin op: aten::_upsample_nearest_exact1d.
03:34:12  Could not find any similar ops to aten::_upsample_nearest_exact1d. This op may not exist or may not be currently supported in TorchScript.
03:34:12  :
03:34:12    File "/home/andres/anaconda3/envs/jupyter_env/lib/python3.8/site-packages/torch/nn/functional.py", line 3896
03:34:12  
03:34:12      if input.dim() == 3 and mode == "nearest-exact":
03:34:12          return torch._C._nn._upsample_nearest_exact1d(input, output_size, scale_factors)
03:34:12                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
03:34:12      if input.dim() == 4 and mode == "nearest-exact":
03:34:12          return torch._C._nn._upsample_nearest_exact2d(input, output_size, scale_factors)
03:34:12  Serialized   File "code/__torch__/torch/nn/functional/___torch_mangle_75.py", line 186
03:34:12            _57 = False
03:34:12          if _57:
03:34:12            _60 = torch._upsample_nearest_exact1d(input, output_size2, scale_factors2)
03:34:12                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
03:34:12            _59 = _60
03:34:12          else:
03:34:12  'interpolate' is being compiled since it was called from 'DynUNet.forward'
03:34:12  Serialized   File "code/__torch__/monai/networks/nets/dynunet.py", line 27
03:34:12    def forward(self: __torch__.monai.networks.nets.dynunet.DynUNet,
03:34:12      x: Tensor) -> Tensor:
03:34:12      _0 = __torch__.torch.nn.functional.___torch_mangle_75.interpolate
03:34:12      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
03:34:12      skip_layers = self.skip_layers
03:34:12      out = (skip_layers).forward(x, )
03:34:12  
03:34:12  
03:34:12  
03:34:12  real	0m26.666s
03:34:12  user	0m16.624s
03:34:12  sys	0m5.826s
03:34:12  Check failed!
```

with
NVIDIA-SMI 465.07       Driver Version: 465.07       CUDA Version: 11.3  
docker `nvcr.io/nvidia/pytorch:22.04-py3`

cc @diazandr3s could you please help look into this one?

**Comment by diazandr3s** [comment]
Thanks, @wyli

I've faced the same issue locally. I'm not sure if this is related to a change made in MONAI or PyTorch. I see this issue is related to jit, right?

I bypass this by using a python virtual environment with Python==3.9.12 and torch==1.11.0

Do you know if there was a recent change made to jit recently?

**Comment by wyli** [comment]
I think the jit is tested in these environment https://github.com/Project-MONAI/MONAI/blob/557c12940e3e31be3f01f8031afcd6c027a8870d/tests/test_dynunet.py#L119 @yiheng-wang-nv any idea?

**Comment by yiheng-wang-nv** [comment]
Hi @diazandr3s , the first line of the notebook is wrong, it misses a comma and should be:
```
!python -c "import monai" || pip install -q "monai-weekly[nibabel, tqdm]"
```

Hi @wyli , I did not meet the same error when using 22.04 with cuda 11.6 and 510.47.03, could you send the link of this test, and let me see how to reproduce the error.

**Comment by yiheng-wang-nv** [comment]
Hi @diazandr3s , could you also post the code which is used to create the `.ts` module? Thanks!

**Comment by wyli** [comment]
> Hi @diazandr3s , could you also post the code which is used to create the `.ts` module? Thanks!

I think it's this one https://github.com/Project-MONAI/tutorials/blob/d8d0d4e6b63fa25a023134cdae9e7306c1ca9230/deepedit/ignite/train.py#L361

**Comment by diazandr3s** [comment]
> Hi @diazandr3s , another small issue is that in
> 
> https://github.com/Project-MONAI/tutorials/blob/d8d0d4e6b63fa25a023134cdae9e7306c1ca9230/deepedit/ignite/train.py#L354
> `args.channels` and `args.dimensions` are not defined in your `ArgumentParser`, could you please also add these args, otherwise error will happen when using `export`

I think this caused the error. Just made a PR https://github.com/Project-MONAI/tutorials/pull/696 fixing this problem. I'll train the model again and update the weights.

Thanks for commenting on this.

**Comment by diazandr3s** [comment]
Hi @wyli, @yiheng-wang-nv,

Just updated the pretrained weights. We shouldn't have this issue again.

Please let me know

**Comment by wyli** [comment]
this is still an issue, according to the latest nightly log.

**Comment by diazandr3s** [comment]
Thanks for opening this issue again, @wyli.

I managed to replicate the problem locally. For this, I've created a python virtual env with the following commands/requirements:

> conda create -n test-tutorial-env python=3.8 pytorch cudatoolkit=11.3 -c pytorch -c nvidia


> Python 3.8.13


> absl-py==1.0.0
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asttokens==2.0.5
attrs==21.4.0
backcall==0.2.0
beautifulsoup4==4.11.1
bleach==5.0.0
cachetools==5.0.0
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.12
cycler==0.11.0
debugpy==1.6.0
decorator==5.1.1
defusedxml==0.7.1
entrypoints==0.4
executing==0.8.3
fastjsonschema==2.15.3
fonttools==4.33.3
google-auth==2.6.6
google-auth-oauthlib==0.4.6
grpcio==1.46.1
idna==3.3
imageio==2.19.1
importlib-metadata==4.11.3
importlib-resources==5.7.1
ipykernel==6.13.0
ipython==8.3.0
ipython-genutils==0.2.0
ipywidgets==7.7.0
itk==5.2.1.post1
itk-core==5.2.1.post1
itk-filtering==5.2.1.post1
itk-io==5.2.1.post1
itk-numerics==5.2.1.post1
itk-registration==5.2.1.post1
itk-segmentation==5.2.1.post1
jedi==0.18.1
Jinja2==3.1.2
jsonschema==4.5.1
jupyter==1.0.0
jupyter-client==7.3.1
jupyter-console==6.4.3
jupyter-core==4.10.0
jupyterlab-pygments==0.2.2
jupyterlab-widgets==1.1.0
kiwisolver==1.4.2
Markdown==3.3.7
MarkupSafe==2.1.1
matplotlib==3.5.2
matplotlib-inline==0.1.3
mistune==0.8.4
monai-weekly==0.9.dev2219
nbclient==0.6.3
nbconvert==6.5.0
nbformat==5.4.0
nest-asyncio==1.5.5
networkx==2.8
nibabel==3.2.2
notebook==6.4.11
numpy==1.22.3
oauthlib==3.2.0
packaging==21.3
pandocfilters==1.5.0
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.1.0
prometheus-client==0.14.1
prompt-toolkit==3.0.29
protobuf==3.20.1
psutil==5.9.0
ptyprocess==0.7.0
pure-eval==0.2.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
Pygments==2.12.0
pyparsing==3.0.9
pyrsistent==0.18.1
python-dateutil==2.8.2
pytorch-ignite==0.4.8
PyWavelets==1.3.0
pyzmq==22.3.0
qtconsole==5.3.0
QtPy==2.1.0
requests==2.27.1
requests-oauthlib==1.3.1
rsa==4.8
scikit-image==0.19.2
scipy==1.8.0
Send2Trash==1.8.0
six==1.16.0
soupsieve==2.3.2.post1
stack-data==0.2.0
tensorboard==2.8.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
terminado==0.13.3
tifffile==2022.5.4
tinycss2==1.1.1
torch==1.10.2
tornado==6.1
tqdm==4.64.0
traitlets==5.2.0
typing_extensions @ file:///opt/conda/conda-bld/typing_extensions_1647553014482/work
urllib3==1.26.9
wcwidth==0.2.5
webencodings==0.5.1
Werkzeug==2.1.2
widgetsnbextension==3.6.0
zipp==3.8.0


The issue comes from the torch version (1.10.2). I've trained the model with torch 1.11.0 and it seems there is an incompatibility of the ts files between these two torch versions. You can see here the solution for this here:  https://discuss.pytorch.org/t/unknown-builtin-op-aten-tensor/62389/2

As I used the DyUNet, I see that's definitely the problem: https://github.com/Project-MONAI/MONAI/blob/dev/monai/networks/nets/dynunet.py#L171
